version: '3.4'

services:
    eavsandbox.web:
        image: ${DOCKER_REGISTRY-}eavsandbox
        build:
            context: .
            dockerfile: EavSandbox.Web/Dockerfile
        depends_on:
            - db

    db:
        image: microsoft/mssql-server-linux:2017-latest
        environment:
            SA_PASSWORD: "!The_password_123"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433